sudo: required
services:
  - docker

before_install:
  - docker build -t eli9000/complex-fib-app -f ./client/Dockerfile.dev ./client

script:
  - docker run eli9000/complex-fib-app npm run test -- --coverage

after_success:
  - docker build -t eli9000/multi-client ./client
  - docker build -t eli9000/multi-nginx ./nginx
  - docker build -t eli9000/multi-server ./server
  - docker build -t eli9000/multi-worker ./worker
  # Login to the Docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push eli9000/multi-client
  - docker push eli9000/multi-nginx
  - docker push eli9000/multi-server
  - docker push eli9000/multi-worker

deploy:
  provider: elasticbeanstalk
  region: us-east-1
  app: complex-fib-app
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-us-east-1-842140652626
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY
