sudo: required
services:
  - docker

before_install:
  - docker build -t eli9000/complex-fib-app -f ./client/Dockerfile.dev ./client

script:
  - docker run eli9000/complex-fib-app npm run test -- --coverage

after_success:
  - docker build -t eli9000/multi-client ./client
  - docker build -t eli9000/multi-nginx ./nginx
  - docker build -t eli9000/multi-server ./server
  - docker build -t eli9000/multi-worker ./worker
  # Login to the Docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push eli9000/multi-client
  - docker push eli9000/multi-nginx
  - docker push eli9000/multi-server
  - docker push eli9000/multi-worker
